# Generated by Django 3.0 on 2019-12-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=2082)),
                ('pub_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('votes_total', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='images/products/')),
                ('icon', models.ImageField(blank=True, upload_to='images/icons/')),
                ('body', models.TextField()),
            ],
        ),
    ]
